
server:
  port: 9000

spring:
  # 主数据源 - PostgreSQL (向量数据，供 Spring AI 使用)
  datasource:
    pgvector:
      url: jdbc:postgresql://${postgresql.host}:5432/mxy_rag_vector_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
          pool-name: VectorDBHikariCP
          minimum-idle: 10
          maximum-pool-size: 12
          connection-timeout: 60000
          idle-timeout: 500000
          max-lifetime: 540000

    # 次要数据源 - MySQL (业务数据)
    mysql:
      url: jdbc:mysql://${mysql.host}:3306/mxy_rag_db?useUnicode=true&characterEncoding=utf-8&autocommit=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Shanghai
      username: ${mysql.username}
      password: ${mysql.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: BusinessDBHikariCP
        minimum-idle: 10
        maximum-pool-size: 12
        connection-timeout: 60000
        idle-timeout: 500000
        max-lifetime: 540000
        connection-test-query: SELECT 1
        auto-commit: true
        leak-detection-threshold: 5000

  application:
    name: mxy-rag-server

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    openai:
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus-latest
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      pgvector:
        table-name: mxy_rag_vector
        initialize-schema: true
        dimensions: 1024
        index-type: hnsw

# MyBatis Plus 配置 (用于 MySQL 业务数据)
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
